"""中文书名 → 标准英文书名 对照表（bookfetch 方案 A：外文原版源搜索用）。

收录规则：
1. 只收中文读者高频搜索的世界文学/哲学经典 + 常见译名变体（如 傲慢和偏见/傲慢与偏见）；
2. 值 = 英文站（古登堡 / 维基文库英文）检索用的标准英文书名；
3. 表外书名走「统一书名翻译接口」——见 n2core._translate_book_title：
   macOS 用系统翻译桥（zh2en），未来在线 provider 走同一接口；
4. 收录条目的英文名须是通行标准名；拿不准的宁缺毋滥（表外有翻译兜底，
   表内错了反而误导——搜出来是另一本书）。
5. 扩充走社区 PR；删改同理。

结构：{中文书名（含变体，各一条）: 标准英文书名}。保持按中文拼音/主题分组。
"""

_CN_TO_EN: dict[str, str] = {
    # ——— 英美经典 ———
    "傲慢与偏见": "Pride and Prejudice",
    "傲慢和偏见": "Pride and Prejudice",
    "理智与情感": "Sense and Sensibility",
    "爱玛": "Emma",
    "曼斯菲尔德庄园": "Mansfield Park",
    "诺桑觉寺": "Northanger Abbey",
    "劝导": "Persuasion",
    "简爱": "Jane Eyre",
    "简·爱": "Jane Eyre",
    "呼啸山庄": "Wuthering Heights",
    "雾都孤儿": "Oliver Twist",
    "大卫·科波菲尔": "David Copperfield",
    "远大前程": "Great Expectations",
    "双城记": "A Tale of Two Cities",
    "艰难时世": "Hard Times",
    "荒凉山庄": "Bleak House",
    "小杜丽": "Little Dorrit",
    "匹克威克外传": "The Pickwick Papers",
    "圣诞颂歌": "A Christmas Carol",
    "名利场": "Vanity Fair",
    "德伯家的苔丝": "Tess of the d'Urbervilles",
    "苔丝": "Tess of the d'Urbervilles",
    "无名的裘德": "Jude the Obscure",
    "远离尘嚣": "Far from the Madding Crowd",
    "卡斯特桥市长": "The Mayor of Casterbridge",
    "还乡": "The Return of the Native",
    "米德尔马契": "Middlemarch",
    "弗洛斯河上的磨坊": "The Mill on the Floss",
    "织工马南": "Silas Marner",
    "亚当·比德": "Adam Bede",
    "红字": "The Scarlet Letter",
    "七角楼": "The House of the Seven Gables",
    "白鲸": "Moby-Dick",
    "汤姆叔叔的小屋": "Uncle Tom's Cabin",
    "瓦尔登湖": "Walden",
    "草叶集": "Leaves of Grass",
    "汤姆索亚历险记": "The Adventures of Tom Sawyer",
    "汤姆·索亚历险记": "The Adventures of Tom Sawyer",
    "哈克贝利·费恩历险记": "Adventures of Huckleberry Finn",
    "王子与贫儿": "The Prince and the Pauper",
    "百万英镑": "The Million Pound Bank Note",
    "野性的呼唤": "The Call of the Wild",
    "白牙": "White Fang",
    "海狼": "The Sea-Wolf",
    "马丁·伊登": "Martin Eden",
    "小妇人": "Little Women",
    "绿山墙的安妮": "Anne of Green Gables",
    "秘密花园": "The Secret Garden",
    "小公主": "A Little Princess",
    "海蒂": "Heidi",
    "木偶奇遇记": "The Adventures of Pinocchio",
    "爱丽丝梦游仙境": "Alice's Adventures in Wonderland",
    "爱丽丝漫游奇境记": "Alice's Adventures in Wonderland",
    "爱丽丝镜中奇遇记": "Through the Looking-Glass",
    "彼得潘": "Peter Pan",
    "彼得·潘": "Peter Pan",
    "柳林风声": "The Wind in the Willows",
    "丛林之书": "The Jungle Book",
    "金银岛": "Treasure Island",
    "诱拐": "Kidnapped",
    "化身博士": "Strange Case of Dr Jekyll and Mr Hyde",
    "杰基尔与海德": "Strange Case of Dr Jekyll and Mr Hyde",
    "血字的研究": "A Study in Scarlet",
    "四签名": "The Sign of the Four",
    "福尔摩斯探案集": "The Adventures of Sherlock Holmes",
    "福尔摩斯冒险史": "The Adventures of Sherlock Holmes",
    "巴斯克维尔的猎犬": "The Hound of the Baskervilles",
    "失落的世界": "The Lost World",
    "时间机器": "The Time Machine",
    "世界大战": "The War of the Worlds",
    "星际战争": "The War of the Worlds",
    "隐形人": "The Invisible Man",
    "隐身人": "The Invisible Man",
    "莫罗博士岛": "The Island of Doctor Moreau",
    "道林·格雷的画像": "The Picture of Dorian Gray",
    "德古拉": "Dracula",
    "弗兰肯斯坦": "Frankenstein",
    "科学怪人": "Frankenstein",
    "白衣女人": "The Woman in White",
    "月亮宝石": "The Moonstone",
    "黑暗的心": "Heart of Darkness",
    "吉姆爷": "Lord Jim",
    "儿子与情人": "Sons and Lovers",
    "查泰莱夫人的情人": "Lady Chatterley's Lover",
    "一个青年艺术家的画像": "A Portrait of the Artist as a Young Man",
    "尤利西斯": "Ulysses",
    "都柏林人": "Dubliners",
    "达洛维夫人": "Mrs Dalloway",
    "到灯塔去": "To the Lighthouse",
    "一间自己的房间": "A Room of One's Own",
    "霍华德庄园": "Howards End",
    "看得见风景的房间": "A Room with a View",
    "印度之行": "A Passage to India",
    "老人与海": "The Old Man and the Sea",
    "太阳照常升起": "The Sun Also Rises",
    "永别了，武器": "A Farewell to Arms",
    "永别了武器": "A Farewell to Arms",
    "丧钟为谁而鸣": "For Whom the Bell Tolls",
    "了不起的盖茨比": "The Great Gatsby",
    "夜色温柔": "Tender Is the Night",
    "人间天堂": "This Side of Paradise",
    "人鼠之间": "Of Mice and Men",
    "愤怒的葡萄": "The Grapes of Wrath",
    "伊甸之东": "East of Eden",
    "麦田里的守望者": "The Catcher in the Rye",
    "杀死一只知更鸟": "To Kill a Mockingbird",
    "喧哗与骚动": "The Sound and the Fury",
    "我弥留之际": "As I Lay Dying",
    "动物农场": "Animal Farm",
    "1984": "Nineteen Eighty-Four",
    "一九八四": "Nineteen Eighty-Four",
    "美丽新世界": "Brave New World",
    "华氏451度": "Fahrenheit 451",
    "华氏451": "Fahrenheit 451",
    "第二十二条军规": "Catch-22",
    "五号屠场": "Slaughterhouse-Five",
    "洛丽塔": "Lolita",
    "在路上": "On the Road",
    "蝇王": "Lord of the Flies",
    "魔戒": "The Lord of the Rings",
    "指环王": "The Lord of the Rings",
    "霍比特人": "The Hobbit",
    "纳尼亚传奇": "The Chronicles of Narnia",
    "狮子、女巫与魔衣橱": "The Lion, the Witch and the Wardrobe",
    "纯真年代": "The Age of Innocence",
    "觉醒": "The Awakening",
    "红色英勇勋章": "The Red Badge of Courage",
    # ——— 法国经典 ———
    "悲惨世界": "Les Miserables",
    "巴黎圣母院": "The Hunchback of Notre-Dame",
    "九三年": "Ninety-Three",
    "基督山伯爵": "The Count of Monte Cristo",
    "三个火枪手": "The Three Musketeers",
    "茶花女": "The Lady of the Camellias",
    "高老头": "Father Goriot",
    "欧也妮·葛朗台": "Eugenie Grandet",
    "红与黑": "The Red and the Black",
    "巴马修道院": "The Charterhouse of Parma",
    "包法利夫人": "Madame Bovary",
    "羊脂球": "Boule de Suif",
    "漂亮朋友": "Bel Ami",
    "老实人": "Candide",
    "社会契约论": "The Social Contract",
    "爱弥儿": "Emile",
    "论人类不平等的起源和基础": "Discourse on Inequality",
    "局外人": "The Stranger",
    "鼠疫": "The Plague",
    "西西弗神话": "The Myth of Sisyphus",
    "恶心": "Nausea",
    # ——— 俄语经典 ———
    "战争与和平": "War and Peace",
    "安娜·卡列尼娜": "Anna Karenina",
    "安娜卡列尼娜": "Anna Karenina",
    "复活": "Resurrection",
    "伊凡·伊里奇之死": "The Death of Ivan Ilyich",
    "罪与罚": "Crime and Punishment",
    "卡拉马佐夫兄弟": "The Brothers Karamazov",
    "白痴": "The Idiot",
    "群魔": "The Possessed",
    "地下室手记": "Notes from Underground",
    "赌徒": "The Gambler",
    "父与子": "Fathers and Sons",
    "死魂灵": "Dead Souls",
    "钦差大臣": "The Government Inspector",
    "当代英雄": "A Hero of Our Time",
    "怎么办": "What Is to Be Done?",
    "牛虻": "The Gadfly",
    "樱桃园": "The Cherry Orchard",
    "三姐妹": "Three Sisters",
    "海鸥": "The Seagull",
    "万尼亚舅舅": "Uncle Vanya",
    # ——— 德语 / 欧洲其它 ———
    "浮士德": "Faust",
    "少年维特的烦恼": "The Sorrows of Young Werther",
    "少年维特之烦恼": "The Sorrows of Young Werther",
    "变形记": "The Metamorphosis",
    "堂吉诃德": "Don Quixote",
    "神曲": "The Divine Comedy",
    "十日谈": "The Decameron",
    "君主论": "The Prince",
    # ——— 拉美 ———
    "百年孤独": "One Hundred Years of Solitude",
    "霍乱时期的爱情": "Love in the Time of Cholera",
    # ——— 希腊罗马 / 古典 ———
    "伊利亚特": "The Iliad",
    "奥德赛": "The Odyssey",
    "埃涅阿斯纪": "The Aeneid",
    "俄狄浦斯王": "Oedipus Rex",
    "安提戈涅": "Antigone",
    "美狄亚": "Medea",
    "理想国": "The Republic",
    "会饮篇": "Symposium",
    "沉思录": "Meditations",
    "形而上学": "Metaphysics",
    "尼各马可伦理学": "Nicomachean Ethics",
    "政治学": "Politics",
    "诗学": "Poetics",
    "乌托邦": "Utopia",
    # ——— 莎士比亚（高频剧目） ———
    "哈姆雷特": "Hamlet",
    "麦克白": "Macbeth",
    "李尔王": "King Lear",
    "奥赛罗": "Othello",
    "奥瑟罗": "Othello",
    "罗密欧与朱丽叶": "Romeo and Juliet",
    "裘力斯·凯撒": "Julius Caesar",
    "恺撒大帝": "Julius Caesar",
    "威尼斯商人": "The Merchant of Venice",
    "仲夏夜之梦": "A Midsummer Night's Dream",
    "无事生非": "Much Ado About Nothing",
    "皆大欢喜": "As You Like It",
    "第十二夜": "Twelfth Night",
    "驯悍记": "The Taming of the Shrew",
    "暴风雨": "The Tempest",
    "理查三世": "Richard III",
    "亨利五世": "Henry V",
    "安东尼与克莉奥佩特拉": "Antony and Cleopatra",
    # ——— 思想 / 社科 ———
    "物种起源": "On the Origin of Species",
    "国富论": "The Wealth of Nations",
    "共产党宣言": "Manifesto of the Communist Party",
    "资本论": "Capital",
    "利维坦": "Leviathan",
    "政府论": "Two Treatises of Government",
    "纯粹理性批判": "Critique of Pure Reason",
    "查拉图斯特拉如是说": "Thus Spake Zarathustra",
    "善恶的彼岸": "Beyond Good and Evil",
    "悲剧的诞生": "The Birth of Tragedy",
    "道德的谱系": "On the Genealogy of Morals",
    "梦的解析": "The Interpretation of Dreams",
    "图腾与禁忌": "Totem and Taboo",
    "乌合之众": "The Crowd",
}
